### ISSUE TITLE
License

### ISSUE THREAD

**Issue by aqw** [mazkolain/xbmc-skinutils#1]
@mazkolain 

Thanks for providing this code, as it should help us work around Kodi's... unfortunate lack of font support in skinned addons.

Is there a license your code is released under?

---Alex

**Comment by mazkolain-zz** [comment]
Hi!

I've just added a BSD style license to the repo.

Also keep in mind that this module uses some quirks in order to support custom fonts on Kodi scripts. Quirks that may prevent your addon from being accepted on the official repo.

Regards,

Mikel

**Comment by aqw** [comment]
@mazkolain Excellent. Thanks! I'll update our license appropriately.

Have the Kodi devs gone on record saying they're not ok with this solution?

---Alex

**Comment by mazkolain-zz** [comment]
Yes, they did:
http://forum.kodi.tv/showthread.php?tid=195104
